Web/Controllers/GenerateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Adapt.Model;
using CloudIntegration;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Web.Services;

namespace Web.Controllers
{
    [Route(BaseConfig.MvcApiRoute)]
    public class GenerateController : Controller
    {
        private ICourseService CourseService { get; }
        private ICourseGenerateService CourseGenerateService { get; }

        public GenerateController(ICourseService courseService, ICourseGenerateService courseGenerateService)
        {
            CourseService = courseService;
            CourseGenerateService = courseGenerateService;
        }

        [HttpGet]
        [Route("List")]
        public async Task<IActionResult> ListAsync()
        {
            var courses = await CourseService.GetAllPackagesAsync();

            return new ObjectResult(courses);
        }

        [HttpGet]
        [Route("Index")]
        public async Task<IActionResult> IndexAsync([FromQuery] string courseId, bool debug, bool usePreview)
        {
            var generatedDataMessage = new List<string>();
            var debugContent = new List<AdaptCourseData>();

            var courseType = usePreview ? CourseFileTypeEnum.Preview : CourseFileTypeEnum.Prod;

            // generate data for course
            var result = await CourseGenerateService.GeneratePackageDataAsync(courseId, usePreview, courseType);
            generatedDataMessage.Add($"[{courseType}] Data for course '{result.Course.CourseName}' and version '{result.Course.CourseVersionVersion?.FirstOrDefault()?.Codename}' have been generated.");

            if (debug)
            {
                debugContent.Add(result.CourseData);
            }

            return new ObjectResult(new
            {
                Result = generatedDataMessage,
                Debug = debugContent
            });
        }

        /// <summary>
        /// Web hook from KC
        /// </summary>
        [HttpPost]
        [Route("UpdateCourse")]
        public async Task<IActionResult> UpdateCourseAsync([FromBody] WebHookModel model)
        {
            if (model == null)
            {
                throw new NotSupportedException($"Invalid web hook model");
            }

            var generatedDataMessage = new List<string>();

            // Generate course data for all courses and versions.
            // Ideally, we would want to regenerate only the item that changes (+ possibly children), but that
            // is not worth the effort right now + there is very limited possibility of identifying in which items certain item is included as modular content.
            // Or there could be more personalized web hooks coming in..
            var projectCourses = await CourseService.GetAllPackagesWithinProjectAsync(model.Message.ProjectId);

            // go through all courses within a project :-(
            foreach (var projectCourse in projectCourses)
            {
                var result = await CourseGenerateService.GeneratePackageDataAsync(projectCourse.CourseId, false, CourseFileTypeEnum.Prod);
                generatedDataMessage.Add($"Data for course '{result.Course.CourseName}' and version '{projectCourse.CourseVersionVersion.FirstOrDefault()?.Codename}' have been generated.");
            }

            return new ObjectResult(generatedDataMessage);
        }

  

    }
}

Web/Controllers/HomeController.cs
using System.Linq;
using System.Threading.Tasks;
using CloudIntegration;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Web.Services;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private ICourseService CourseService { get; }
        private IFileService FileService { get; }

        public HomeController(ICourseService courseService, IFileService fileService)
        {
            CourseService = courseService;
            FileService = fileService;
        }

        public async Task<IActionResult> Index()
        {
            var courses = await CourseService.GetAllPackagesAsync();

            return View(courses.Select(m => new SupportedPackageDto()
            {
                PreviewLog = FileService.GetCourseLog(m.Package.CourseId, m.Package.Language.First().Codename, CourseFileTypeEnum.Preview),
                ProdLog = FileService.GetCourseLog(m.Package.CourseId, m.Package.Language.First().Codename, CourseFileTypeEnum.Prod),
                Package = m.Package,
                ProjectId = m.ProjectId,
            }).ToList());
        }
    }
}

Web/Views/Home/Index.cshtml
@model List<Web.Models.SupportedPackageDto>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kentico Cloud Course generator</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>

    <section class="section">
        <div class="container">
            <h1 class="title">
                Courses
            </h1>
            <p class="subtitle">
                Use to generate & test course data
            </p>

            <div>

                @foreach (var supportedCourse in Model)
            {

                <div class="card" style="margin-top: 16px">
                    <header class="card-header has-background-info">
                        <p class="card-header-title has-text-white">
                            @supportedCourse.Package.DisplayTitle
                        </p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            Course Id: <strong>@supportedCourse.Package.CourseId</strong>
                        </div>
                        <div class="content">
                            <div>
                                Project id: <strong>@supportedCourse.ProjectId</strong>
                            </div>
                        </div>
                        <div class="content">
                            Description: @supportedCourse.Package.Description
                        </div>

                        <div class="content">
                            Production data
                            @if (supportedCourse.ProdLog != null)
                            {
                            <ul>
                                <li>Pages: <strong>@supportedCourse?.ProdLog?.Pages</strong></li>
                                <li>Blocks: <strong>@supportedCourse?.ProdLog?.Blocks</strong></li>
                                <li>Articles: <strong>@supportedCourse?.ProdLog?.Articles</strong></li>
                                <li>Components: <strong>@supportedCourse?.ProdLog?.Components</strong></li>
                            </ul>
                            }
                            else
                            {
                                <em>Production log not available</em>
                            }
                        </div>

                        <div class="content">
                            Preview data
                            @if (supportedCourse.PreviewLog != null)
                            {
                            <ul>
                                <li>Pages: <strong>@supportedCourse?.PreviewLog?.Pages</strong></li>
                                <li>Blocks: <strong>@supportedCourse?.PreviewLog?.Blocks</strong></li>
                                <li>Articles: <strong>@supportedCourse?.PreviewLog?.Articles</strong></li>
                                <li>Components: <strong>@supportedCourse?.PreviewLog?.Components</strong></li>
                            </ul>
                            }
                            else
                            {
                                <em>Preview log not available</em>
                            }
                        </div>

                        <footer class="card-footer">
                            <div class="card-footer-item">
                                <a target="_blank" href="@Url.ActionLink("Index", "Generate", new {courseId = supportedCourse.Package.CourseId, projectId = supportedCourse.ProjectId, debug = true, usePreview = false})">Rebuild prod</a>
                                &nbsp;<span class="is-size-6">( @supportedCourse.ProdLog?.TimestampUTc)</span>
                            </div>
                            <div class="card-footer-item">
                                <a target="_blank" href="@Url.ActionLink("Index", "Generate", new {courseId = supportedCourse.Package.CourseId, projectId = supportedCourse.ProjectId, debug = true, usePreview = true})">Rebuild preview</a>
                                &nbsp;<span class="is-size-6">( @supportedCourse.PreviewLog?.TimestampUTc)</span>
                            </div>
                        </footer>
                    </div>
                </div>
            }
            </div>
        </div>
    </section>
</body>
</html>